### ISSUE TITLE
Bug: Unable to remove task due date

### ISSUE THREAD

**Issue by m-vdv** [guillaumebriday/todolist-frontend-vuejs#3]
After adding a due date to a task, it is impossible to remove it. (Only change it)

**Comment by guillaumebriday** [comment]
Exact, I'm on it

**Comment by guillaumebriday** [comment]
Fixed in https://github.com/guillaumebriday/todolist-backend-laravel/commit/c76c9cd5947478cd19a8ea3801fc4790a6582813 

It's in production 

Thanks for the issue !
