### ISSUE TITLE
Question: Where is the Laravel API code?

### ISSUE THREAD

**Issue by connecteev** [guillaumebriday/todolist-frontend-vuejs#6]
Thanks for the demo at https://todolist.guillaumebriday.xyz/
Looks cool but I'm wondering if there's an end-to-end example that uses Laravel for the API /backend? Am I missing something?

**Comment by connecteev** [comment]
Nevermind, I found it! Will try to get it working...Thanks!

**Comment by guillaumebriday** [comment]
It is literary the first line of the README haha

**Comment by connecteev** [comment]
Yes sorry Guillaume thanks for the speedy response :D :)
