### ISSUE TITLE
Bug: Todos don't show up after a new account is created, unless you reload the page

### ISSUE THREAD

**Issue by connecteev** [guillaumebriday/todolist-frontend-vuejs#7]
Issue:
Create a brand new account at https://todolist.guillaumebriday.xyz/

You land on https://todolist.guillaumebriday.xyz/app/active
Then, start adding Todos, but NONE of them show up until you reload the page.

I think this is a bug here.

**Comment by guillaumebriday** [comment]
What ? It works perfectly fine for me.

Can you give me more details ?

**Comment by pifaace** [comment]
Hi, I'm not sure what do you mean.
You say, when you add a new task and click on "Add" button, the task doesn't show up ? 

Works for me as well

**Comment by connecteev** [comment]
Okay the steps are:
1. go here; https://todolist.guillaumebriday.xyz/register and create an account:
https://prnt.sc/o4uo8e
2. You land at https://prnt.sc/o4uomk
3. Click add task, add a name https://prnt.sc/o4up1q and then hit "Add"
4. NOTHING shows up...you're back at https://prnt.sc/o4uqdu (but you can see Active=1)
However, the data does get saved and is visible if you reload the page.
Notice this only happens the first time after you create an account...so there's some bug in the initialization going on.

**Comment by guillaumebriday** [comment]
Haaa ok nice one ! Can’t fix that before beginning of July... If you can submit a PR that’s could be great !

Thank you @connecteev

**Comment by connecteev** [comment]
I'm SUPER new to vue :D and found this when exploring examples.
But if I find a fix will let you know..otherwise I don't mind waiting till July :)

**Comment by guillaumebriday** [comment]
Hey !

I fixed it in this commit https://github.com/guillaumebriday/todolist-frontend-vuejs/commit/47bc4add97e98e5e676caf406e0982dc0a63dd84

It happened even on account already created but without tasks in the first place.

Watcher are not triggered when components are created in Vuejs.

Thank you !

**Comment by connecteev** [comment]
Thanks for the fix, but I wasn't able to get this codebase working on my localhost.

**Comment by guillaumebriday** [comment]
Open a new issue if needed, thanks
